### ISSUE TITLE
xml布局中用NestedScrollView嵌套recyclerview，广告控件滑动不了

### ISSUE THREAD

**Issue by jackom** [giswangsj/RvParallaxImageView#1]
xml布局中用NestedScrollView嵌套recyclerview，广告控件滑动不了

**Comment by giswangsj** [comment]
这个当然滑动不了了，NestedScrollView嵌套recyclerview，recyclerview的复用就失效了，所有的item的一次性创建了，recyclerview也监听不到滚动事件了，官方也不推荐这种做法。你有什么需求，试试CoordinatorLayout能不能实现

**Comment by jackom** [comment]
> 这个当然滑动不了了，NestedScrollView嵌套recyclerview，recyclerview的复用就失效了，所有的item的一次性创建了，recyclerview也监听不到滚动事件了，官方也不推荐这种做法。你有什么需求，试试CoordinatorLayout能不能实现

好的，我试下 CoordinatorLayout，谢谢了。

**Comment by jackom** [comment]
我使用  CoordinatorLayout 可以的了，先关闭了。
